name: nutripic
description: "Nutripic App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  firebase_core: ^3.5.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  go_router: ^14.2.7
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
