name: nutripic
description: "Nutripic App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.4
  go_router: ^14.2.7
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  camerawesome: ^2.0.0
  image_gallery_saver: ^2.0.3
  kakao_flutter_sdk_user: ^1.9.6
  provider: ^6.1.2
  sign_in_with_apple: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
